from . import test_elmis_program
from . import test_elmis_inventory_sync
from . import test_elmis_inventory_sync_run
from . import test_elmis_inventory_sync_wizard
from . import test_product_product
from . import test_res_config_settings
from . import test_location_inventory_view
from . import test_stock_lot
from . import test_stock_quant_adjustment
from . import test_stock_move_line_transfer
from . import test_stock_scrap
from . import test_elmis_outbox
from . import test_sale_order_line
