{
    "name": "eLMIS Integration",
    "summary": "Foundation model extensions for OpenLMIS product and lot sync",
    "version": "16.0.1.0.0",
    "category": "Inventory",
    "author": "MOH Lesotho",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "lesotho_base",
        "product",
        "stock",
        "web",
    ],
    "data": [
        "data/elmis_config_defaults.xml",
        "data/elmis_inventory_sync_cron.xml",
        "security/ir.model.access.csv",
        "views/elmis_inventory_sync_wizard_views.xml",
        "views/elmis_inventory_sync_run_views.xml",
        "views/res_config_settings_views.xml",
        "views/product_product_views.xml",
        "views/stock_lot_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "elmis_integration/static/src/scss/elmis_sync_status.scss",
            "elmis_integration/static/src/js/elmis_sync_status.js",
            "elmis_integration/static/src/xml/elmis_sync_status.xml",
        ],
    },
    "installable": True,
    "application": False,
}
