from . import elmis_program
from . import elmis_outbox
from . import elmis_inventory_sync
from . import elmis_inventory_sync_run
from . import elmis_inventory_sync_wizard
from . import product_product
from . import res_config_settings
from . import sale_order_line
from . import stock_lot
from . import stock_quant
from . import stock_scrap
from . import stock_move
from . import stock_move_line
