{
    "name": "Lesotho Sale",
    "summary": "Lesotho Sale Customizations",
    "version": "16.0.1.0.0",
    "category": "Localization",
    "author": "eLMIS Development Team",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "base",
        "stock",
        "sale",
        "mrp",
    ],
    "data": [
        "views/menu_overrides.xml",
        "views/action_overrides.xml",
        "views/view_overrides.xml",
        "security/dispensing_security.xml",
        "security/dispensing_groups.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "application": False,
}
